on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version name"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch
  push:
    branches:
      - "master"

jobs:
  createTag:


  deploy:
